services:
  - type: web
    name: mindex-taskmanager-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    publishDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://mindex-taskmanager.onrender.com

  - type: web
    name: mindex-taskmanager
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 5005
    preDeployCommand: python scripts/init_db.py
    envVars:
      - fromGroup: taskmanager-secrets